version: '2'
services:
    ipam-app:
        image: ipam
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ipam-postgresql:5432/IPAM
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ipam-postgresql:
        extends:
            file: postgresql.yml
            service: ipam-postgresql
