version: '2'
services:
    ipam-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/IPAM/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=IPAM
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
